### ISSUE TITLE
Error when editing server after first start

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-rsp-ui#101]
Steps:

1) Start Red Hat RSP Server
2) Pick Widlfly -> Edit Server -> edit vs.args.override.string value. In my case i edited -Xmx to 2048m
3) Save (it should succeed)
4) Start Wildfly 
5) Stop it
6) Edit Server -> edit vs.args.override.string value again.
7) Error

**Comment by robstryker** [comment]
I really can't figure out how to replicate this.  I've been trying for a long while and just can't get the error you guys see. I think I must be doing something wrong.

**Comment by robstryker** [comment]
I do notice a few things:
1) When you change heap size without setting overrides to true, the change is not persisted
2) a new editor is opened displaying the returned response from the server

So possible issues we *can* fix are:
  1) Try to error if a changed value and is not accepted...
  2) I don't think we should open a new editor with the returned value? Is there some way to simply replace the existing editor's content?

**Comment by lstocchi** [comment]
I'm able to replicate it by using extensions from the marketplace but it disappears if i debug it by using local rsp server. Maybe it was fixed somehow in the new rsp server? Btw if we release the rsp-server master it should be fixed.

I don't remember why we are opening a new editor everytime we save server properties but it can be easily changed. Creating PR.

I guess we should add an information message or a new field (like a comment/explanation) in the json (server properties) to remember the override has to be set to true or `vm.args.override.string` and `program.args.override.string` will not be saved.

**Comment by lstocchi** [comment]
Closing it as https://github.com/redhat-developer/vscode-rsp-ui/pull/102 was merged
