### ISSUE TITLE
Remove one server view

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/vscode-rsp-ui#112]
Currently we have two servers views which gives us a lot of troubles and not so many advantages apparently, so my proposal is to remove one of them.

The new version of Vscode allows users to move views inside the ide so there is no reason to keep two views. If someone prefer to have the servers view inside the explorer can drag and drop it from the activity bar or viceversa. 

By looking at https://github.com/redhat-developer/rsp-server-community/issues/31 it's like there is an error from the ui such as 
![image](https://user-images.githubusercontent.com/49404737/86109779-09905900-bac5-11ea-800c-b2fb09b5adb2.png)
![image](https://user-images.githubusercontent.com/49404737/86109850-1e6cec80-bac5-11ea-842b-3889dbf887a7.png)

If you focus on the servers View, it will prompt an error regarding serversAB, if you focus on serversAB it will prompt an error on the servers view. This is the result using VScode Insiders. 

I also think https://github.com/redhat-developer/vscode-rsp-ui/issues/106 is related to this.

So before to dig into this i wanted to raise a flag and ask you, are we sure we want to maintain both views or we could go back to having only one? WDYT? @robstryker @odockal

**Comment by odockal** [comment]
@lstocchi  I do not object to keep just one (if causing troubles). But which one?

**Comment by robstryker** [comment]
I believe we should keep the first one we had. It's the one I use most (but maybe I'm biased?) I have always imagined people don't want to switch to the activity bar. But maybe I'm wrong. 

I vote to remove AB

**Comment by lstocchi** [comment]
I don't have any preference about the one to keep as views are movable now ... so if users are used to use the activity bar can drag and drop the view from explorer to AB and/or viceversa.

**Comment by robstryker** [comment]
We don't have any data on which one users use more often, AB or main tab. However, main tab was there longer, and shows up right when users are looking at their project, and is also referenced more in the videos and documentation (since it was added first).  

Remove the newcomer AB.
