### ISSUE TITLE
Can't add file deployment under target

### ISSUE THREAD

**Issue by epomatti** [redhat-developer/vscode-rsp-ui#130]
I'm trying to add a file deployment to my WildFly server, however I can't add a file under the `target/` directory.

![image](https://user-images.githubusercontent.com/6530769/90455570-bf8f2100-e0cc-11ea-9127-5f62740822e4.png)

**Comment by lstocchi** [comment]
Hi @epomatti, can you please tell me how you do that? If you right-click on the server, click the `Add deployment` action and follow the workflow, doesn't it work for you?

**Comment by epomatti** [comment]
@lstocchi I am very sorry, I was going to the wrong directory.

**Comment by lstocchi** [comment]
@epomatti don't worry, glad it works :) For anything else, just open a new issue. Thank you!!

**Comment by epomatti** [comment]
@lstocchi I've opened this issue as well, but on a diff repo. Maybe you want to check it out 😁 

https://github.com/redhat-developer/vscode-java/issues/1582

**Comment by lstocchi** [comment]
I guess it is related to https://github.com/redhat-developer/rsp-server project. I noticed that behavior as well lately, as a turnaround i stop and start the server several time, and after a couple of times all servers are displayed correctly. There should be an issue on the server, maybe some race condition (don't know). The rsp-server repo owner is on PTO but i'll give it a look in the next days if i find some free time. Sorry for the inconvenience
