### ISSUE TITLE
Feature Request/Discussion - Open "Add Deployment" in current project root dir

### ISSUE THREAD

**Issue by epomatti** [redhat-developer/vscode-rsp-ui#131]
Opening this for discussion:

When adding a deployment (either file or exploded) the default directory to be opened in the command palette should be the current project root, instead of the home dir.

It would be convenient for most cases to have that opening that way.

(Also when pasting the path the command palette is not responding to changes)

![vscode](https://user-images.githubusercontent.com/6530769/90524586-a1fd9e00-e144-11ea-9065-99aec5f8dd6f.gif)

**Comment by robstryker2** [comment]
Good suggestion

**Comment by robstryker2** [comment]
Topic branch is here:  https://github.com/robstryker/vscode-rsp-ui/pull/new/issue131

Will merge it once i regain my github creds. Ugh.
