### ISSUE TITLE
Cannot open Native file manager dialog when Output channel is active

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#141]
1. Start RSP server
2. Create new app. server like WF
3. Start server (output is active)
4. On WF server tree item call Add Deployment
5. Choose File deployment
6. Expect: File manager is opened so the use can choose path to the war
Actually no dialog appears and info notification is shown:
```
File system provider for output:extension-output-%236 is not available.
```

**Comment by odockal** [comment]
@robstryker  @lstocchi I hope that you see the issue in changes in PR. window.activeTextEditor returns strange things, or could have returned when unexpected editor/channel/tab is active. Also I have changed priority of what default URI should be chosen. Check and comment in PR please.

**Comment by robstryker** [comment]
Great fix!  I had this bug once two days ago but couldn't replicate it!
