### ISSUE TITLE
Server stuck in 'starting' after changing http port in standalone.xml

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-rsp-ui#150]
Steps to reproduce:
 - create a server (WF/EAP)
 - go to `Server Actions` -> `Edit Configuration File`
 - change `<socket-binding name="http" port="${jboss.http.port:8080}"/>` to something other than 8080
 - start the server

-> server actually starts up correctly, just the UI is still reporting `starting`

**Comment by robstryker** [comment]
Steps to fix:

-     create a server (WF/EAP)
-     go to Server Actions -> Edit Configuration File
-     change <socket-binding name="http" port="${jboss.http.port:8080}"/> to something other than 8080
-     right-click the server, edit it to open the editor
-     add property jboss.server.port with value you used in config file
-    start the server

**Comment by robstryker** [comment]
Works as expected
