### ISSUE TITLE
Add possibility to change configuration file in UI

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/vscode-rsp-ui#151]
Hi, 

the server configuration file should be also possible to change in UI. Now only option is to use **Edit Server** and change parameters  "args.override.boolean" and "args.program.override.string".

Thanks!
Josef

**Comment by robstryker** [comment]
Open editor, add property wildfly.server.config.file  with value standalone-ha.xml or similar. Should work as expected.

**Comment by robstryker** [comment]
When creating the server it should ask you as one of the optional parameters if you want to change the config file. If not, your option is to edit the server and set wildfly.server.config.file field.  Those are the only two options. Vs-code doesn't have a great UI option. 

I've verified that changing wildfly.server.config.file to the right field accuratrely updates the launch flags to include --server-config=standalone-ha.xml
