### ISSUE TITLE
Edit Configuration File opens only standalone.xml

### ISSUE THREAD

**Issue by jkopriva** [redhat-developer/vscode-rsp-ui#152]
Steps to reproduce:

1. Create new server
2. Click on Edit Server
3. Change parameters to: "args.override.boolean": "true",   "args.program.override.string": "-mp \"/Users/jkopriva/.rsp/redhat-server-connector/runtimes/installations/wildfly-2100finalruntime/wildfly-21.0.0.Final/modules\" org.jboss.as.standalone --server-config=standalone-full.xml", 
4. and save.
5. Click on server -> Server Actions... -> Edit Configuration Files -> standalone.xml is opened, not standalone-full.xml

**Comment by robstryker** [comment]
If you add server property wildfly.server.config.file with value of standalone-ha.xml, the edit configuration file should open the correct file.

**Comment by robstryker** [comment]
I've verified this works as expected.
