### ISSUE TITLE
Any other-than-server application running on 8080 will prevent to work with server adapters (wf, eap) properly

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#159]
2. Open VSCode and servers view
2. Assert: RSP gets started
3. Create server (eap or wildfly)
4. Assert: Server is created and its state is stopped
5. Stop RSP
6. Start some app running on 8080 (container, server)
6. Start RSP
7. Assert: RSP is stared
8. Assert: eap or wf server is detected as stopped
Actual result: Server is marked as started, it cannot be stopped (there is connectionRefused error) or terminated. Thus it cannot be even deleted via remove server.
Only way to do so it to kill the app running on the port.

**Comment by robstryker** [comment]
I believe you should be able to edit the server, change the port in the server adapter, change the port in the standalone.xml, and then should be able to make use of the server adapter.

**Comment by robstryker** [comment]
At the very least, attempts to 'terminate' should mark teh server as stopped I guess.

**Comment by robstryker** [comment]
I've pushed https://github.com/redhat-developer/rsp-server/pull/642   which ensures that wildfly / eap servers will actually terminate and not poll the server to ensure the terminate succeeded and keep an accurate state. Best I can do bc there's no other way for me to verify what exactly is running on 8080.
