### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Autenic** [redhat-developer/vscode-rsp-ui#169]
- Issue Type: `Bug`
- Extension Name: `vscode-rsp-ui`
- Extension Version: `0.23.7`
- OS Version: `Windows_NT x64 10.0.18363`
- VS Code version: `1.55.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by robstryker** [comment]
... Hi. Can you please explain what behavior you think is buggy?
