### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ntthang-dev** [redhat-developer/vscode-rsp-ui#172]
- Issue Type: `Bug`
- Extension Name: `vscode-rsp-ui`
- Extension Version: `0.23.8`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by robstryker** [comment]
This issue is missing data, please paste the diagnostic information. It would also be helpful if you could describe what you were doing when this happened
