### ISSUE TITLE
Add Local Server/Download Server context menu available on RSP/Server items and broken

### ISSUE THREAD

**Issue by jrichter1** [redhat-developer/vscode-rsp-ui#2]
At any given time both the RSP tree items and the runtimes tree items have the two options in their context menus.
Both end in an immediate error
```
Unable to detect any runtime:  Extension backend error - failed to contact the rsp server.
```

**Comment by jrichter1** [comment]
Update: the context menu items are also available on deployments.

**Comment by lstocchi** [comment]
as a reminder this should fix this issue https://github.com/redhat-developer/vscode-server-connector/pull/368

**Comment by jrichter1** [comment]
This is going to get confusing :)  Can you open it against this repo then? I think the original one is no longer going to serve the UI.
