### ISSUE TITLE
Create Server as a View in Activity bar

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#22]
I think that having servers "view" under vscode explorer section is not that visible and fancy for such feature. We might think of have its own action item in activity bar with its own view, etc. Similarly to  ie. openshift, wdyt?

![Screenshot_20190711_103904](https://user-images.githubusercontent.com/19164299/61035823-24575280-a3c8-11e9-9fdd-952d464c4810.png)

**Comment by robstryker** [comment]
+1 I like this idea...

**Comment by odockal** [comment]
@robstryker @lstocchi @jeffmaury Still good idea? I kinda like it. :)

**Comment by robstryker** [comment]
@jeffmaury  What do you think? It sounds like a good idea but it'd probably require rework on the UI side.  I have no idea how much at all. But before we do a cost evaluation, do we think it's even a good idea?
