### ISSUE TITLE
Allow for addition of projectName in the debug

### ISSUE THREAD

**Issue by mixtoism** [redhat-developer/vscode-rsp-ui#226]
vscode java debugger requires a projectName field in the debugger in order to properly find the related classes. this change should be implemented in the start debugging request to vscode adding the appropiate field.

example of a working launch.json 
```javascript
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Debug in Wildfly",
            "request": "attach",
            "hostName": "localhost",
            "port": "52356",
            "projectName": "projectName" --> this name matches the artifact id tag in the pom.xml
        },
```

Appropiate changes should be made in src/debug/javaDebugSession.ts:33-42
```javascript
private async startDebugger(port: string) {
        this.port = port;
        vscode.debug.startDebugging(undefined, {
            type: 'java',
            request: 'attach',
            name: 'Debug (Remote)',
            hostName: 'localhost',
            port,
           projectName, // this could be asked via the prompt to the user or acquired somehow
        });
    }
```

**Comment by robstryker** [comment]
Pinging @fbricon privately on this issue to see if he has any advice. Specifically, some users may deploy multiple projects to a server and thus need multiple project names to be part of the launch. Asking to see if that's possible at all.

**Comment by robstryker** [comment]
I opened https://github.com/microsoft/vscode-java-debug/issues/1197  to allow the possibility to add multiple projects, since users may deploy multiple deployments to a single server. But until that is addressed, I'll go with a solution like you've suggested.

**Comment by Ahmed654321653** [comment]
admin

**Comment by Ahmed654321653** [comment]
550
