### ISSUE TITLE
Sort server versions by  decreasing version

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-rsp-ui#236]
When selecting a server to download, I think it makes sense to display the most recent versions of a server first, as opposed to this: 

<img width="875" alt="Screenshot 2022-07-27 at 17 49 14" src="https://user-images.githubusercontent.com/148698/181292443-34da87b4-a364-43c4-a831-87d32e6033b5.png">

**Comment by robstryker** [comment]
Current unreleased implementation is to display as follows:

![image](https://user-images.githubusercontent.com/630383/181299384-7be16233-657d-4807-ba7f-1f5d1e9cc6be.png)

Feel free to re-open if you think this still sucks.
