### ISSUE TITLE
The oldest, no longer maintained servers are displayed 1st

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-rsp-ui#237]
When downloading a server, we're presented with a really poor choice of old servers. 
<img width="871" alt="Screenshot 2022-07-27 at 17 55 00" src="https://user-images.githubusercontent.com/148698/181294329-e4073b4c-3030-4b59-b5b0-1396d21833fc.png">

This list should be curated. Worst case scenario, offer a More Servers... option at the end, that would show the really old stuff.

**Comment by robstryker** [comment]
Fixed by https://github.com/redhat-developer/vscode-rsp-ui/issues/149  
 not yet released
