### ISSUE TITLE
Failed to register client capabilities in time

### ISSUE THREAD

**Issue by mkhabibullin** [redhat-developer/vscode-rsp-ui#240]
The "Remote Server Protocol UI" extension doesn't start.

Runtime status log has the errors:
- Connection got disposed.
- Connection got disposed.
- Failed to register client capabilities in time
- Failed to get server handles in time

![image](https://user-images.githubusercontent.com/8382339/182362790-6dfd4627-888c-45cd-b101-5a66dffb01c1.png)

VS Code settings.json:
{
    "typescript.updateImportsOnFileMove.enabled": "always",
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "files.exclude": {
        "**/.classpath": true,
        "**/.project": true,
        "**/.settings": true,
        "**/.factorypath": true
    },
    "window.menuBarVisibility": "compact",
    "redhat.telemetry.enabled": false,
    "workbench.colorTheme": "Default High Contrast Light",
    "window.zoomLevel": -1,
    "editor.minimap.enabled": false,
    "editor.renderWhitespace": "all",
    "workbench.sideBar.location": "right",
    "java.server.launchMode": "Standard",
    "java.jdt.ls.java.home": "C:\\Program Files\\Java\\jdk-18.0.1",
    "rsp-ui.enableStartServerOnActivation": [
        {
            "id": "redhat.vscode-community-server-connector",
            "name": "Community Server Connector",
            "startOnActivation": true
        }
    ]
}

Environment:
WIndows 10, VS Code - 1.69.2

version of "Remote Server Protocol UI" - v0.23.11

Is there any chance to fix it?

**Comment by MaratKhabibullinTR** [comment]
the fix seems to be described here - https://github.com/redhat-developer/rsp-server-community/issues/31#issuecomment-652232905
removing the file .lock fixed the issue

the issue can be closed

**Comment by mkhabibullin** [comment]
the fix seems to be described here - https://github.com/redhat-developer/rsp-server-community/issues/31#issuecomment-652232905
removing the file .lock fixed the issue

the issue can be closed
