### ISSUE TITLE
How do I run the Tomcat with a specific version of JDK?

### ISSUE THREAD

**Issue by ZhouLuquan** [redhat-developer/vscode-rsp-ui#244]
My default JDK is Open JDK 17 which I can run VS Code and its extensions. However, my Java project and Tomcat should run with JDK 1.6. How do I run the Tomcat with a specific version of JDK?

**Comment by jtsaich** [comment]
There is a JAVA Home setting in the extension: /Users/jack/Library/Java/JavaVirtualMachines
There is also `"java.configuration.runtimes"` need to make sure the version is correct

**Comment by robstryker** [comment]
I've just noticed that the VM option is not showing up when creating a new tomcat server like it does for wildfly, so I've opened a new issue to track that:   https://github.com/redhat-developer/rsp-server-community/issues/151
