### ISSUE TITLE
Unable to install Tomcat Server on Windows with white space in server.base.dir

### ISSUE THREAD

**Issue by ThierrySudre** [redhat-developer/vscode-rsp-ui#248]
I am trying to create a Tomcat server 9.x with VSC windows version, but the server never start with following error:
![tomcat](https://user-images.githubusercontent.com/47594758/192384979-b6a6b215-7125-4fb8-a6bd-178d7c0197b3.jpg)

my server json config file is as follow:
![tomcat2](https://user-images.githubusercontent.com/47594758/192385253-3e8905e9-d620-4d0a-8eea-7c91dad4cb22.jpg)

Now if I move all downloaded Tomcat files in a folder like C:\tomcat and update the json file according to this path, Tomcat starts successfully.

Issue seems to be the white space in tomcat path.

**Comment by robstryker** [comment]
Replicated on linux

**Comment by robstryker** [comment]
I think i fixed it with this https://github.com/redhat-developer/rsp-server-community/pull/147

Not 100% sure bc i'm not on windows but, I'm pretty sure?

**Comment by ThierrySudre** [comment]
Correction seems consistent, I will check when delivered in the next version.
I have try to add single quotes in args.vm.override.string in server settings but even if I set "args.override.boolean": "true", the override string is ignored.
