### ISSUE TITLE
Tomcat Server staying in "Starting" status and after a while stops

### ISSUE THREAD

**Issue by ThierrySudre** [redhat-developer/vscode-rsp-ui#249]
This is a trick to know if you change the Tomcat Connector port inside server.xml conf file like this :
![tomcat3](https://user-images.githubusercontent.com/47594758/192738683-2d55f69f-a26c-44ac-bdfa-37a8d72a8cd6.jpg)

As you can see, i am using port 80 instead of installation default which is 8080.
You must also update the server config JSON file (right click on server and "Edit Server") by setting the same port (80):

![tomcat4](https://user-images.githubusercontent.com/47594758/192739858-b2a4a363-5d01-4680-8227-6c96d3a13946.jpg)
As the extension is checking the fact that the server is realling started by testing server reply on configured port. If the ports configured in JSON file and Server.xml file are not the same, the server will stay in "Starting" status and never goes to "Started" status.

**Comment by jeffmaury** [comment]
This is by design. The port specified in server JSON file has the semantic of use this port to check if server is properly started and not start this server using this port
