### ISSUE TITLE
Is it possible to ignore compatibility checks?

### ISSUE THREAD

**Issue by ninelore** [redhat-developer/vscode-rsp-ui#251]
My company runs its project on wildfly 11 with jdk 11 without issues. I'd like to switch from netbeans to vscode but the compatibility check is keeping mefrom doing so. Is there a way to ignore the check?

**Comment by robstryker** [comment]
Can you remind me or show a screenshot of which compatibility check you're referring to?

**Comment by ninelore** [comment]
> Can you remind me or show a screenshot of which compatibility check you're referring to?

![image](https://user-images.githubusercontent.com/21343557/199851719-2a3d9970-022a-4c1f-a4f8-0e4c2364b812.png)

**Comment by robstryker** [comment]
The first version that is supposed to run on JDK11 is [WildFly 15](http://wildfly.org/news/2018/12/13/WildFly15-Final-Released/). With that said, there's no current way to circumvent the compatability check. 

I have no real plans to change this, but, you could, in theory, go find the file in charge of your wildfly adapter (`~/.rsp/redhat-server-connector/servers/WildFly\ 11`) and see if you can replace the line `  "org.jboss.tools.rsp.server.typeId": "org.jboss.ide.eclipse.as.wildfly.110"` with .as.wildfly.150.  This may make the compatibility check pass. 

I don't *believe* anything else would be negatively effected by this. You're basically telling the tooling to treat this server as if it's a wf15 server.

**Comment by robstryker** [comment]
If this workaround does in fact work, I'd appreciate it if you can report back adn close the issue ;)

**Comment by ninelore** [comment]
It seems to work. Thanks!
