### ISSUE TITLE
Support Apache Tomcat 10.1.x

### ISSUE THREAD

**Issue by loxcel** [redhat-developer/vscode-rsp-ui#257]
rsp-ui can create a server for Tomcat 10.0.x but not 10.1.x.

According to

https://tomcat.apache.org/tomcat-10.0-eol.html

Apache Tomcat 10.0.x is no longer supported.

According to

https://tomcat.apache.org/whichversion.html

"Users of Tomcat 10.0 should be aware that Tomcat 10.0 has now reached [end of life](https://tomcat.apache.org/tomcat-10.0-eol.html). Users of Tomcat 10.0.x should upgrade to Tomcat 10.1.x or later."

Can you please add support for Tomcat 10.1.x ?

Thanks

**Comment by mohitsuman** [comment]
@robstryker can you please have a look at this.

**Comment by loxcel** [comment]
Are there any updates to this request?

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server-community/pull/154
