### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by JavierLagorio** [redhat-developer/vscode-rsp-ui#262]
Type: <b>Bug</b>

Unable to start the server: Extension backend error - rsp error - community server connector failed to start - typeerror: cannot read properties of undefined (reading 'map')

Extension version: 0.23.13
VS Code version: Code 1.74.3 (97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:59:02.252Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.89GB (0.84GB free)|
|Process Argv|--crash-reporter-id df4df31a-274c-4abe-86cd-24940aea5dc7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
pyind779:30647091
f6dab269:30613381
a9j8j154:30646983

```

</details>

**Comment by robstryker** [comment]
Any further information, like what server you were attempting to start? Tomcat? Karaf? What version?

**Comment by diorgeneseugenio** [comment]
Same here!

Extension version: 0.23.13
VS Code version: 1.75.1
OS version: 12.6.3


https://user-images.githubusercontent.com/20167342/219031033-655d1505-cb63-46c8-89b7-25a8108dc2eb.mp4

**Comment by robstryker** [comment]
I've tried to unify and clean up the error reporting here in the case of an unexpected error. It MAY fix your issue, or it MAY just make the underlying cause more readily accessible / visible. 

Please let me know how it looks.

**Comment by robstryker** [comment]
I believe this issue was fixed.
