### ISSUE TITLE
Creating new server should offer server name by default

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#28]
I can image that some default server name is offered when creating new local server (depending on chosen server location, config? ). Check that such server name is not already used should be implemented as well. 

I know that this might be a bit challenging as no server type is known during creating local server.

**Comment by robstryker** [comment]
I guess in theory we could just move server name to an optional setting, and, if its unset, generate something like we do in jbt during creation or also like during download-runtime workflow.

**Comment by odockal** [comment]
I can imagine that. No we are not able during server creation to let it empty, which is also alright.
