### ISSUE TITLE
Tomcat 9.0 server stop few minutes after start without any output

### ISSUE THREAD

**Issue by Tenebrosful** [redhat-developer/vscode-rsp-ui#282]
Hello,

I'm using the extension but there is a problem, the Tomcat server stop working after few minutes without any error or output logs.

I tested with CLI vanilla Tomcat or other extension like [Local Tomcat](https://github.com/snehaljha/local-tomcat) and everything looks fine.

`Windows 10 Pro 22H2`
`Tomcat 9.0`
`Runtime Server Protocol UI v0.24.7`

If i can share you any more details feel free to asking but like i said there is no output / logs (that i know) about this.

PS: It always display `Starting` even when startup finished and the server is available to use

**Comment by robstryker** [comment]
Let's go with this other issue instead. 

https://github.com/redhat-developer/rsp-server-community/issues/206
