### ISSUE TITLE
Contextual Menu showing where it shouldn't

### ISSUE THREAD

**Issue by Tenebrosful** [redhat-developer/vscode-rsp-ui#283]
Hi, i currently have a problem.

The contextual menu `Server Actions...` and `Edit Server` is showing on things that it shouldn't (leading to undefined errors of course)

Example: 
Here on right click on Java Project File ![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/ec6e7cba-cdf0-43fb-9688-483df8ba88f9)

Here on Task Explorer Window ![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/606d39f1-6c7b-4462-baef-7f77ce7de705)

Here on i18n-ally tab ![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/1432618b-a3e0-48cc-b601-baebbd974f51)

And because that's not suppose to be here, clicking on the option lead to an (normal) error ![image](https://github.com/redhat-developer/rsp-server-community/assets/48710891/bafd2d7a-3ed6-488b-97c8-2e9caa86117d)

**Comment by robstryker** [comment]
Can you verify what version of the rsp-ui extension you have installed?
