### ISSUE TITLE
Not able to publish large project in time

### ISSUE THREAD

**Issue by bartonhammond** [redhat-developer/vscode-rsp-ui#287]
The Extension documents that the Publish can be async but when I edit the `settings.json` it appears it's not a valid option.

Also, the menu option "Edit Server" is only available when I start VS Code.  Once I use it, it won't work a 2nd time.

![image](https://github.com/redhat-developer/vscode-rsp-ui/assets/1282364/51ed3803-643b-4688-8646-090a0a938202)

![image](https://github.com/redhat-developer/vscode-rsp-ui/assets/1282364/b1f256a2-fea8-4076-b101-7692ecf02131)

![image](https://github.com/redhat-developer/vscode-rsp-ui/assets/1282364/9d1dfad7-ae59-41bb-ab51-e33588b8bc41)

**Comment by robstryker** [comment]
Seems a problem in the package.json.  Fixing it.   Opened https://github.com/redhat-developer/vscode-rsp-ui/pull/288

Please open a separeate issue for edit server issue.
