### ISSUE TITLE
Servers view stealing focus on hot code replace

### ISSUE THREAD

**Issue by walterdvalle** [redhat-developer/vscode-rsp-ui#305]
While on Run and Debug view, if you save a Java file, Hot Code Replace is invoked and Servers view (in Explorer view) steals focus navigating from Run and Debug to Explorer view.
If you are in a debug moment, it's important to stay in Run and Debug because you probably need to inspect variables and folow some values in Watch view. It's not desired do navigate back to Explorer without consent. See the animation attached. ![Image](https://github.com/user-attachments/assets/09c8049e-7c35-4754-89b4-2ef6227bd9b6)

Please, adjust this strange behavior.

**Comment by robstryker** [comment]
You can change your settings here: 
![Image](https://github.com/user-attachments/assets/0adad09d-dd9f-45d7-98a4-8daa4cd9c479)

**Comment by walterdvalle** [comment]
Aparently the problem is the line 234 in serverExplorer.ts 

tmpViewer.reveal

```
    public selectNode(data: RSPState | ServerStateNode): void {
        this.nodeSelected = data;
        //const tmpViewer = this.viewer;
        //tmpViewer.reveal(data, { focus: false, select: true });
    }

```
It forces the SERVERS view to jump in front of your eyes.

**Comment by walterdvalle** [comment]
Can you confirm this?

**Comment by walterdvalle** [comment]
https://vscode-api.js.org/interfaces/vscode.TreeView.html#:~:text=reveal,-reveal(element%3A%20T&text=Reveals%20the%20given%20element%20in,default%20revealed%20element%20is%20selected.

Reveals the given element in the tree view. If the tree view is not visible then the tree view is shown and element is revealed.

**Comment by walterdvalle** [comment]
Running a local compiled vsix file here. Removed tmpViewer.reveal
Everything is ok now.

**Comment by robstryker** [comment]
Thanks for the report. I'll see what I can do to incorporate your fix!

**Comment by walterdvalle** [comment]
Thanks a lot!

**Comment by robstryker** [comment]
I've added your fix to the codebase. 

Thanks!
