### ISSUE TITLE
Implement support for RSP Server Action Workflows

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-rsp-ui#32]
Server Actions are now a thing. A server can expose any number of arbitrary actions for a user to run. These actions can theoretically be anything (setup-cdk,  change a setting or property, delete some cache folder in the runtime, etc etc etc).  

These need to be exposed via a menu item on a given runtime (ex: wildfly 12) that reads "Server Actions...."    When the user clicks on that, the API request to get a list of actions for the server from RSP should be executed. The list of action names should be selectable in quickpick.  

Once the user selects an action name, handling the workflow (two-way communication for filling otu a list of prompts, similar to download runtime) should be executed.

**Comment by lstocchi** [comment]
Closing as PR was merged
