### ISSUE TITLE
Should use the selected server in "Servers" view when deploying project

### ISSUE THREAD

**Issue by adietish** [redhat-developer/vscode-rsp-ui#53]
steps:
1. ASSERT: have wildfly server defined (ex. wildfly 17)
1. ASSERT: have project in your workspace (ex. kitchensink)
1. EXEC: select server in "Servers" view (ex. wildfly 17)
1. EXEC: in project select the war in the target folder for your project (ex. kitchensink/target/kitchensink.war) and pick "Run on Server" from context menu

Result:
I get prompted to select the server.
![image](https://user-images.githubusercontent.com/25126/64128119-2da3e080-cdb5-11e9-9151-131afa5ec004.png)

Expected result:
I would love vscode to use the server that I selected in the "Servers" view.

**Comment by robstryker** [comment]
I am highly skeptical of this one. Often times users select things in different views and no longer pay attention to what the selection is in various views. This could easily lead to a user deploying something to the wrong server with no ability to override it. They could get very confused if they aren't aware that the servers view has a selection that is relevant.

**Comment by jeffmaury** [comment]
Or can we display the selected server at the top of the list of servers ?

**Comment by adietish** [comment]
We can pre-select the server that's selected in the servers view.

**Comment by robstryker** [comment]
Those seem like good ideas. Much better than automatically using the selected one.  +1  good idea guys
