### ISSUE TITLE
Extension backend error when attempting to publish

### ISSUE THREAD

**Issue by bubnick** [redhat-developer/vscode-rsp-ui#64]
When trying to publish an exploded deployment (and occasionally with a file deployment as well), I am receiving the error `Unable to publish (Full) to the server: Extension backend error - failed to publish in time`.

Is there a configurable timeout on publish, or somewhere else that can be adjusted to help prevent this error?

**Comment by lstocchi** [comment]
Hi @bubnick , did you try to increase the deployment timeout inside standalone.xml? 

```
...
<system-properties>
    <property name="jboss.as.management.blocking.timeout" value="900"/>
</system-properties>
...
<profile>
    ...
    <subsystem xmlns="urn:jboss:domain:deployment-scanner:2.0">
        <deployment-scanner path="deployments" relative-to="jboss.server.base.dir" 
          scan-interval="5000" deployment-timeout="900" 
          runtime-failure-causes-rollback=
            "${jboss.deployment.scanner.rollback.on.failure:false}"/>
    </subsystem> 
    ...
</profile>
...
```

After you edit standalone.xml file just make sure the "args.override.boolean" flag is set to true.

Detailed steps:
1) Right-click your server -> Edit Server
2) Is "program.args.override.string" property visible? Go to step 5. 
3) Is "program.args.override.string" not visible? Set "args.override.boolean" to true, save and close.
4) Right-click your server -> click on "Edit Server" again
5) Now you should have "program.args.override.string" flag there. This means that you can now change your standalone.xml file and if you set "args.override.boolean" to true before starting the server, your standalone.xml file will be used.
6) After you changed your standalone.xml file, saved it, set "args.override.boolean" to true, you can start your server.

**Comment by bubnick** [comment]
Hey @lstocchi I've increased the deployment timeout inside the standalone (up to 9000), but am still receiving the same timeout when trying to deploy an exploded deployment (shortly after publishing). Deploying with just the file seems to be working without timing out though.

**Comment by lstocchi** [comment]
@bubnick thank you for the feedback, i'll give a look at why we have this problem with exploded deployment. I'll keep you updated.

**Comment by robstryker** [comment]
Hi @bubnick  

The issue shouldn't be in your standalone.xml at all. In fact, this is more indicating that the UI is waiting too long for a response from the rsp-server (not the wildfly server), which indicates that the publish itself (copying of files etc) is taking too long. 

Is your project very large? The timeout for this is about 7 seconds I believe, so it'd need to be a pretty big project for this to be taking too long. 

We have a few options here. One would be to allow users to customize the timeouts for various calls from UI to server. Problem is, there's lots of different calls, and it may be too many settings for the users to feel comfortable. 

Another option is to make the publish asynchronous and let the rsp-server notify the UI of any errors once publish has completed. In this way, the publish request would return almost immediately with something like executing only extremely simple / fast checks on the status to make sure publish SHOULD be ok (ie destination folders etc exist) and then later inform you when the publish has completed. 

Let me know your thoughts here.

**Comment by bubnick** [comment]
Yes, we have a fairly large project (36 MB), but more so several thousand files within the project which would explain why an exploded view would take longer and hit that timeout.

Seven seconds does sound about right for when I was experiencing the error.

Speaking on the user end, an asynchronous deploy with minimal checks at the start would be the most ideal implementation. This would also have the added benefit of the extension working "right out of the box" per se.

**Comment by robstryker** [comment]
I've opened https://github.com/redhat-developer/rsp-server/issues/485   for next version

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/issues/485  was merged

**Comment by fredngo** [comment]
Still happening for me as of v0.23.13 -- my exploded WAR file is about 483 MB so it's quite a large project...

![Uploading Screen Shot 2022-09-14 at 12.41.30 PM.png…]()
