### ISSUE TITLE
CDK/Minishift server adapter should not offer eap/wf server's option in context menu items

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#67]
Namely: Add deployment, publish options, restart in debug.

**Comment by robstryker** [comment]
These actions are rsp-ui actions, not eap/wf actions.  It's true that cdk/minishift do not support them. but it'd be a bit hard to hide them.

**Comment by odockal** [comment]
Duplicate of https://github.com/redhat-developer/vscode-server-connector/issues/226.
