### ISSUE TITLE
CDK's adapter server action Run command with arg. does not work

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#68]
1. Have created CDK server adapter
2. Server action: setup-cdk
3. ASSERT: setup-cdk is called
4. Have the cdk started
5. ASSERT: CDK is started
6. Server action -> Add service catalog
7. ASSERT: operation is performed:
```Adding service-catalog ...
I1010 15:26:49.364367   15545 interface.go:26] Installing "openshift-service-catalog" ...
I1010 15:26:49.385824   15545 apply_template.go:81] Installing "service-catalog"
I1010 15:26:51.807514   15545 interface.go:41] Finished installing "openshift-service-catalog"
```

8. Server Action -> Run command with arg...
9. ASSERT: command is performed
Actual: Unable to execute action Extension backend error - error loading actions: null

**Comment by robstryker** [comment]
I am not able to replicate this.  
CDK 3.3,   Run command with arg...     "openshift version"
Result: 
   openshift v3.7.14
   kubernetes v1.7.6+a08f5eeb62
   etcd 3.2.8

I am not able to replicate this at this time.

**Comment by odockal** [comment]
@robstryker What I experience is that input box is hidden at the moment I choose the option and so it explains the null in error message.

**Comment by odockal** [comment]
@lstocchi Could you please check it out if you can replicate? Thanks

**Comment by lstocchi** [comment]
I tried and i'm not able to replicate it bc i have several errors before step 6 so it's not working for me too.  I'll need to investigate more. Btw which CDK version are you using?

**Comment by odockal** [comment]
@lstocchi It is latest cdk-3.9.0

**Comment by lstocchi** [comment]
@odockal after cleaning up my machine i was able to do all the steps without any error. Which command do you run? (I used "openshift version" as rob)

**Comment by odockal** [comment]
@lstocchi As I said above, I do not get the input box where I can actually write a command, so that's the problem. But I might have some older version used locally, will check it out just to be sure.

**Comment by lstocchi** [comment]
@odockal ah yes, it can be. We merged a PR which fixed other workflow/action issues 3-4 days ago. Maybe those commits fixed this problem too. Let us know :)

**Comment by odockal** [comment]
That was it. I had some older ui. So it is working. Closing this, sorry for bothering.
