### ISSUE TITLE
Running CDK edit server ends up with error

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#69]
I have CDK started and try to edit server: editing server home and startup program args, ends up with error:

```
There are missing/invalid required attributes for server type org.jboss.tools.rsp.server.minishift.servertype.impl.CDKServerType@492537cc
```

Error does not say much

**Comment by robstryker** [comment]
It'd be great if you could clarify exactly what was done here

**Comment by robstryker** [comment]
Error is in rsp-server. See https://github.com/redhat-developer/rsp-server/issues/486

**Comment by robstryker** [comment]
https://github.com/redhat-developer/rsp-server/pull/487
