### ISSUE TITLE
Can't remove old deployments from wildfly9 server (in vscode's list)

### ISSUE THREAD

**Issue by lampsbr** [redhat-developer/vscode-rsp-ui#78]
Hi,

This is my failing workflow: 

- I open vscode, it shows my wildfly9 server (stopped) with 2 deployments: a `1.0` version of my project and a `1.1` version. I'm naming these versions just to illustrate it. I don't run 2 versions at the same time, they actually have the same .war name (myproject.war). This `1.0` version was removed weeks ago.
- The deployments directory shows only one .war file, corresponding to the newer `1.1`version. It's status is failed right now.
- I start wildfly 9 with right click > start server.
- It deploys the `1.1` version. The server status is (Started) (Unknown). Both deployments get the status (Unknown) (Unknown).
- I run a `mvn package`, in order to generate a new .war file for my project (v`1.1`).
- The rsp server extension gets it and redeploy my project.
- It's correctly deployed, runs in browser. Server status stays (Started) (Unknown), the "ghost" project stays (Unknown) (Unknown), and my `1.1`project now has status (Started) (Synchronized).
- If I right click the ghost project > remove project, it's status changes to (Unknown) (- Publish required), and server's status changes to (Started) (Full Publish Required).
- If I right click the server > Full publish, I instantly get the error message saying Unable to publish (Full) to the server: Extension backend error - publishing server wildfly-9.0.2.final   Source: Remote server protocol ui (extension).

**Comment by robstryker** [comment]
Closing as it's fixed in the newest master.
