### ISSUE TITLE
CRC adapter server action 'Run setup-crc' throws an error even though it is executed

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#95]
1. Get CRC 1.3 server adapter
2. Ctx. menu Server Actions -> Run setup-crc
3. Action is executed, output is shown
Actually all is alright except that error pops up with message:
Error: Unable to execute action Extension backend error - RSP UI (extension)

**Comment by lstocchi** [comment]
The UI receive a wrong cancelWorkflowResponse from the server. https://github.com/redhat-developer/rsp-server/pull/522 should fix it.

**Comment by robstryker** [comment]
Pushed
