### ISSUE TITLE
Servers palette command 'Remove deployment' does not list server with that deployment

### ISSUE THREAD

**Issue by odockal** [redhat-developer/vscode-rsp-ui#97]
This happen only when deployment was just added and not yet fully published.

**Comment by lstocchi** [comment]
@odockal could you give me more info when this happened? i think i misunderstood the problem or i was unable to replicate it.
What i did was: start rsp provider -> start wildfly (with autopublish disabled) -> right-click add new deployment (picked a war file) -> ctrl + p to open palette -> choose remove deployment -> here i can see my server and then the deployment. have you done something different?

**Comment by odockal** [comment]
Oh, I forgot to mentioned that this happens when wf server is stopped. We still allow to deploy apps when server is stopped, so we should probably allow to erase it as well.

**Comment by lstocchi** [comment]
Tried it with wf server stopped but i can see the server and deployment without any problem. @robstryker can you try it and see if you are able to replicate it?

**Comment by robstryker** [comment]
I'm not able to replicate. @odockal  ?

**Comment by odockal** [comment]
YES:
![VSCode-remove_deployment](https://user-images.githubusercontent.com/19164299/95250325-3e295480-081a-11eb-9882-8c7bbe43ca88.gif)
